apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system 
data: 
  mapUsers: |
    - userarn: arn:aws:iam::404180347284:user/simple_bank_test
      username: github-cli
      groups:
        - system:masters