apiVersion: apps/v1

kind: Deployment

metadata:
  name: simple-bank-api-deployment

  labels:
    app: simple-bank-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: simple-bank-api

  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 404180347284.dkr.ecr.us-east-2.amazonaws.com/simplebank:59b7f3a2b4ab3f76d80f320603f319d9207328a2
          ports:
            - containerPort: 8080
