  # This workflow will build a golang project
  # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

  name: Run unit tests 

  on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

  jobs:

    test:
      name: Test
      runs-on: ubuntu-latest
      services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres
            # Provide the password for postgres
          env:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: root
            POSTGRES_DB: simple_bank
          # Set health checks to wait until postgres has started
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
      
      - name: Install golang-migration
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Check out code into the Go module directory
        uses: actions/setup-go@v3

      - name: Test
        run: make test
